(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';const m=Array.from("\ud83d\udc35\ud83d\udc21\ud83d\udc36\ud83d\udc28\ud83d\udc38\ud83e\udd8a\ud83d\udc37\ud83d\udc22\ud83d\udc31\ud83d\udc26\ud83d\udc2f\ud83d\udc34\ud83e\udd8b\ud83d\udc2e\ud83d\udc2d\ud83e\udd84\ud83d\udc30\ud83d\udc3c\ud83d\udc24\ud83d\udc39\ud83d\udc32\ud83d\udc1f\ud83e\udd81\ud83d\udc19\ud83e\udd82\ud83e\udd80"),n=Array.from("\ud83d\udd37\ud83d\udfe5\ud83d\udfe1\ud83d\udfe9\ud83d\udd35\u2b55\ud83d\udd36\ud83d\udfe2\ud83d\udfe6\ud83d\udd34\ud83d\udfe8");
n.push(m[Math.floor(Math.random()*m.length)]);
var v=function(a,c){var b,e;const k=null===(e=null===(b=c.sender)||void 0===b?void 0:b.tab)||void 0===e?void 0:e.id;if(null!=k){p("got connection from Tag Assistant on tab %s",k);a.i.tabs.update(k,{autoDiscardable:!1});var f=a.h.get(k);null!=f?f.port=c:(f={port:c,j:new Set},a.h.set(k,f));c.onMessage.addListener(h=>{if("CONTAINER_DETAILS"===h.data.type){const g=h.data.data.nonce,d=a.s.get(g);a.s.delete(g);q(h,d)}else f.j.forEach(g=>{const d=a.g.get(g);d&&("CLEAR_COOKIE"===h.data.type?d.l=!1:d.l||(d.l=
!0,u(a,g)),d.frames.forEach(l=>{q(h,l)}))})});c.onDisconnect.addListener(()=>{p("port to Tag Assistant tab %s closed",k);f.port=void 0})}},y=function(a,c){var b,e,k;const f=null===(e=null===(b=c.sender)||void 0===b?void 0:b.tab)||void 0===e?void 0:e.id,h=null===(k=c.sender)||void 0===k?void 0:k.frameId;p("got connection from tab %s, frame %s",f,h);if(null!=f&&null!=h){a.i.tabs.update(f,{autoDiscardable:!1});var g=a.g.get(f);null==g&&(g=w(void 0),a.g.set(f,g));var d=g.frames.get(h);null!=d?d.port=
c:(d=x(a,c),g.frames.set(h,d));c.onMessage.addListener(l=>{var r,t;null!=g.m&&("CONTAINER_STARTING"===l.data.type&&a.s.set(l.data.data.nonce,d),l.data.emoji=d.emoji,l.source="EXTENSION",null===(t=null===(r=a.h.get(g.m))||void 0===r?void 0:r.port)||void 0===t?void 0:t.postMessage(l))});c.onDisconnect.addListener(()=>{p("port to tab %s, frame %s closed",f,h);d.port=void 0})}},u=function(a,c,b=0){a.i.tabs.executeScript(c,{file:"api/content_script_bin.js",runAt:"document_start",allFrames:!0,frameId:b,
matchAboutBlank:!0},()=>{const e=a.i.runtime.lastError;e&&p("error while injecting Tag Assistant API on tab %s, frame %s, error: %o",c,b,e.message)})},q=function(a,c){null!==c&&void 0!==c&&c.port&&(a.data.emoji=c.emoji,a.source="EXTENSION",c.port.postMessage(a))},w=function(a){return{m:a,frames:new Map,l:!0}},x=function(a,c){c={port:c,emoji:n[a.o]};a.o++;a.o>=n.length&&(a.o=0);return c};function p(...a){console.log(...a)};new class{constructor(){this.i=chrome;this.h=new Map;this.g=new Map;this.o=0;this.s=new Map;this.i.runtime.onConnectExternal.addListener(a=>{"TAG_ASSISTANT_EXTENSION_PORT"===a.name&&v(this,a)});this.i.runtime.onConnect.addListener(a=>{y(this,a)});this.i.webNavigation.onCreatedNavigationTarget.addListener(({tabId:a,sourceTabId:c,url:b})=>{b=new URL(b);b.hostname.endsWith(".google.com")&&null!=b.searchParams.get("restart_tag_assistant")?(this.h.has(c)||((b=this.g.get(c))?(b.m=a,b.l=!0):this.g.set(c,
w(a)),u(this,c),(b=this.h.get(a))?b.j.add(c):this.h.set(a,{j:new Set([c])})),b=!0):b=!1;if(b=!b)b=this.h.get(c),null!==b&&void 0!==b&&b.port?(b.j.add(a),(b=this.g.get(a))?b.m=c:this.g.set(a,w(c)),b=!0):b=!1,b=!b;if(b){var e;(b=this.g.get(c))&&b.l&&(c=this.g.get(a),b=b.m,c?c.m=b:this.g.set(a,w(b)),null!=b&&(null===(e=this.h.get(b))||void 0===e?void 0:e.j.add(a)))}});this.i.tabs.onRemoved.addListener(a=>{p("tab %s removed",a);var c=this.h.get(a);if(c){this.h.delete(a);for(const b of c.j)if(c=this.g.get(b))c.l=
!1}this.g.delete(a);for(const b of this.h.values())b.j.delete(a)});this.i.webNavigation.onCommitted.addListener(({tabId:a,frameId:c,url:b})=>{"https://tagassistant.google.com"!==(new URL(b)).origin&&(b=this.g.get(a),(null===b||void 0===b?0:b.l)&&u(this,a,c))});this.i.runtime.onMessageExternal.addListener((a,c,b)=>{b({})})}};}).call(this);
