(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k=this||self,l=/^[\w+/_-]+[=]{0,2}$/,m=null,n=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&l.test(a)?a:""},p=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},q=function(a,b){function e(){}e.prototype=b.prototype;a.m=b.prototype;a.prototype=new e;a.prototype.constructor=a;a.l=function(c,d,h){for(var g=Array(arguments.length-2),f=2;f<arguments.length;f++)g[f-2]=arguments[f];return b.prototype[d].apply(c,
g)}},r=function(a){return a};function t(a){a:{var b=null===a||void 0===a?void 0:a.type;if("string"!==typeof b)b=!1;else switch(b){case "PIPE_MESSAGE":case "DISCONNECT":case "API_INSTALLED":b=!0;break a;default:b=!1}}if(b)a:if(a=null===a||void 0===a?void 0:a.source,"string"!==typeof a)b=!1;else switch(a){case "PAGE":case "EXTENSION":b=!0;break a;default:b=!1}return b};function u(a){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{const b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(u,Error);u.prototype.name="CustomError";var v=function(a,b){a=a.split("%s");for(var e="",c=a.length-1,d=0;d<c;d++)e+=a[d]+(d<b.length?b[d]:"%s");u.call(this,e+a[c])};q(v,u);v.prototype.name="AssertionError";
var w=function(a,b,e,c){var d="Assertion failed";if(e){d+=": "+e;var h=c}else a&&(d+=": "+a,h=b);throw new v(""+d,h||[]);},y=function(a,b,e){a||w("",null,b,Array.prototype.slice.call(arguments,2))},z=function(a,b){throw new v("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},A=function(a,b,e){"string"!==typeof a&&w("Expected string but got %s: %s.",[p(a),a],b,Array.prototype.slice.call(arguments,2))};var B;var E=function(a,b){this.h=a===C&&b||"";this.i=D};E.prototype.toString=function(){return"Const{"+this.h+"}"};var F=function(a){if(a instanceof E&&a.constructor===E&&a.i===D)return a.h;z("expected object of type Const, got '"+a+"'");return"type_error:Const"},D={},C={};var H=class{constructor(a,b){this.g=b===G?a:""}};H.prototype.toString=function(){return"TrustedResourceUrl{"+this.g+"}"};var G={};(class{constructor(a,b){this.j=b===I?a:""}}).prototype.toString=function(){return this.j.toString()};var I={};const J=new E(C,"Resource is Const encoded with chrome.runtime.getURL(\u2026).");var L=function(a){var b=F(K);b=chrome.runtime.getURL(b);A(F(J),"must provide justification");var e=F(J);y(!/^[\s\xa0]*$/.test(e),"must provide non-empty justification");if(void 0===B){e=null;var c=k.trustedTypes;if(c&&c.createPolicy)try{e=c.createPolicy("goog#html",{createHTML:r,createScript:r,createScriptURL:r})}catch(x){k.console&&k.console.error(x.message)}B=e}b=(e=B)?e.createScriptURL(b):b;b=new H(b,G);a:{try{var d=a&&a.ownerDocument,h=d&&(d.defaultView||d.parentWindow);h=h||k;if(h.Element&&h.Location){var g=
h;break a}}catch(x){}g=null}if(g&&"undefined"!=typeof g.HTMLScriptElement&&(!a||!(a instanceof g.HTMLScriptElement)&&(a instanceof g.Location||a instanceof g.Element))){g=typeof a;if("object"==g&&null!=a||"function"==g)try{var f=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(x){f="<object could not be stringified>"}else f=void 0===a?"undefined":null===a?"null":typeof a;z("Argument is not a %s (or a non-Element, non-Location mock); got: %s","HTMLScriptElement",
f)}b instanceof H&&b.constructor===H?f=b.g:(z("expected object of type TrustedResourceUrl, got '"+b+"' of type "+p(b)),f="type_error:TrustedResourceUrl");a.src=f;(f=a.ownerDocument&&a.ownerDocument.defaultView)&&f!=k?f=n(f.document):(null===m&&(m=n(k.document)),f=m);f&&a.setAttribute("nonce",f)};const K=new E(C,"api/tag_assistant_api_bin.js");(function(a,b){const e=b.document.createElement("script");L(e);b.document.documentElement.appendChild(e);e.remove();let c=void 0;b.document.addEventListener("__TAG_ASSISTANT_API_MESSAGE",d=>{if(t(d.detail)&&(d=d.detail,"PAGE"===d.source))switch(d.type){case "API_INSTALLED":c=a.runtime.connect();c.onDisconnect.addListener(()=>{c=void 0});null===c||void 0===c?void 0:c.onMessage.addListener(h=>{b.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:h}))});break;case "PIPE_MESSAGE":d.origin=
b.origin;null===c||void 0===c?void 0:c.postMessage(d);break;case "DISCONNECT":null===c||void 0===c?void 0:c.disconnect()}})})(chrome,window);}).call(this);
