/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var h,m=this||self,p=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},q=function(a){var b=p(a);return"array"==b||"object"==b&&"number"==typeof a.length},t=function(a,b){function c(){}c.prototype=b.prototype;a.na=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.la=function(d,f,e){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[f].apply(d,g)}},u=function(a){return a};function x(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}t(x,Error);x.prototype.name="CustomError";var y=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,f=0;f<d;f++)c+=a[f]+(f<b.length?b[f]:"%s");x.call(this,c+a[d])};t(y,x);y.prototype.name="AssertionError";
var z=function(a,b,c,d){var f="Assertion failed";if(c){f+=": "+c;var e=d}else a&&(f+=": "+a,e=b);throw new y(""+f,e||[]);},A=function(a,b,c){a||z("",null,b,Array.prototype.slice.call(arguments,2));return a},B=function(a,b){throw new y("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},C=function(a,b,c){"number"!==typeof a&&z("Expected number but got %s: %s.",[p(a),a],b,Array.prototype.slice.call(arguments,2));return a},aa=function(a,b,c){"string"!==typeof a&&z("Expected string but got %s: %s.",
[p(a),a],b,Array.prototype.slice.call(arguments,2))};var ba=Array.prototype.forEach?function(a,b,c){A(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f="string"===typeof a?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function ca(a){return Array.prototype.concat.apply([],arguments)};var la=function(a,b){if(b)a=a.replace(da,"&amp;").replace(ea,"&lt;").replace(fa,"&gt;").replace(ha,"&quot;").replace(ia,"&#39;").replace(ja,"&#0;");else{if(!ka.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(da,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ea,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(fa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ha,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ia,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ja,"&#0;"))}return a},da=/&/g,ea=/</g,fa=/>/g,ha=/"/g,ia=/'/g,
ja=/\x00/g,ka=/[\x00&<>"']/;var D;var F=function(a,b){this.Z=a===E&&b||"";this.ha=ma};F.prototype.ea=!0;F.prototype.da=function(){return this.Z};F.prototype.toString=function(){return"Const{"+this.Z+"}"};var na=function(a){if(a instanceof F&&a.constructor===F&&a.ha===ma)return a.Z;B("expected object of type Const, got '"+a+"'");return"type_error:Const"},ma={},E={};var H=function(a,b,c){this.X=c===G?a:"";this.ba=b};H.prototype.ja=!0;H.prototype.ea=!0;H.prototype.da=function(){return this.X.toString()};H.prototype.toString=function(){return"SafeHtml{"+this.X+"}"};
var oa=function(a){if(a instanceof H&&a.constructor===H)return a.X;B("expected object of type SafeHtml, got '"+a+"' of type "+p(a));return"type_error:SafeHtml"},qa=function(a){if(a instanceof H)return a;var b="object"==typeof a,c=null;b&&a.ja&&(c=a.ba);return pa(la(b&&a.ea?a.da():String(a)),c)},G={},pa=function(a,b){if(void 0===D){var c=null;var d=m.trustedTypes;if(d&&d.createPolicy)try{c=d.createPolicy("goog#html",{createHTML:u,createScript:u,createScriptURL:u})}catch(f){m.console&&m.console.error(f.message)}D=
c}a=(c=D)?c.createHTML(a):a;return new H(a,b,G)},ra=new H(m.trustedTypes&&m.trustedTypes.emptyHTML||"",0,G);var sa=function(a,b,c){aa(na(a),"must provide justification");A(!/^[\s\xa0]*$/.test(na(a)),"must provide non-empty justification");return pa(b,c||null)};var ta={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},ua=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=oa(ra);return!b.parentElement}),va=function(a,b){if(ua())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=oa(b)};var ya=function(a){return-1!=a.indexOf("&")?"document"in m?wa(a):xa(a):a},wa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var c=m.document.createElement("div");return a.replace(za,function(d,f){var e=b[d];if(e)return e;"#"==f.charAt(0)&&(f=Number("0"+f.substr(1)),isNaN(f)||(e=String.fromCharCode(f)));if(!e){e=sa(new F(E,"Single HTML entity."),d+" ");if(c.tagName&&ta[c.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+c.tagName+
".");va(c,e);e=c.firstChild.nodeValue.slice(0,-1)}return b[d]=e})},xa=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:return"#"!=c.charAt(0)||(c=Number("0"+c.substr(1)),isNaN(c))?b:String.fromCharCode(c)}})},za=/&([^;\s<&]+);?/g;var Aa="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""},Ba=function(){};Ba.prototype.next=function(){throw Aa;};Ba.prototype.ia=function(){return this};var I=function(a,b){this.v={};this.j=[];this.T=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};h=I.prototype;h.ca=function(){return this.g};h.A=function(){K(this);for(var a=[],b=0;b<this.j.length;b++)a.push(this.v[this.j[b]]);return a};h.I=function(){K(this);return this.j.concat()};h.R=function(a){return L(this.v,a)};
h.equals=function(a,b){if(this===a)return!0;if(this.g!=a.ca())return!1;b=b||Ca;K(this);for(var c,d=0;c=this.j[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};var Ca=function(a,b){return a===b};I.prototype.clear=function(){this.v={};this.T=this.g=this.j.length=0};I.prototype.remove=function(a){return L(this.v,a)?(delete this.v[a],this.g--,this.T++,this.j.length>2*this.g&&K(this),!0):!1};
var K=function(a){if(a.g!=a.j.length){for(var b=0,c=0;b<a.j.length;){var d=a.j[b];L(a.v,d)&&(a.j[c++]=d);b++}a.j.length=c}if(a.g!=a.j.length){var f={};for(c=b=0;b<a.j.length;)d=a.j[b],L(f,d)||(a.j[c++]=d,f[d]=1),b++;a.j.length=c}};h=I.prototype;h.get=function(a,b){return L(this.v,a)?this.v[a]:b};h.set=function(a,b){L(this.v,a)||(this.g++,this.j.push(a),this.T++);this.v[a]=b};
h.addAll=function(a){if(a instanceof I)for(var b=a.I(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};h.forEach=function(a,b){for(var c=this.I(),d=0;d<c.length;d++){var f=c[d],e=this.get(f);a.call(b,e,f,this)}};h.clone=function(){return new I(this)};h.toObject=function(){K(this);for(var a={},b=0;b<this.j.length;b++){var c=this.j[b];a[c]=this.v[c]}return a};
h.ia=function(a){K(this);var b=0,c=this.T,d=this,f=new Ba;f.next=function(){if(c!=d.T)throw Error("The map has changed since the iterator was created");if(b>=d.j.length)throw Aa;var e=d.j[b++];return a?e:d.v[e]};return f};var L=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Da=function(a){if(a.A&&"function"==typeof a.A)return a.A();if("string"===typeof a)return a.split("");if(q(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},Ea=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(q(a)||"string"===typeof a)ba(a,b,c);else{if(a.I&&"function"==typeof a.I)var d=a.I();else if(a.A&&"function"==typeof a.A)d=void 0;else if(q(a)||"string"===typeof a){d=[];for(var f=a.length,e=0;e<f;e++)d.push(e)}else for(e in d=
[],f=0,a)d[f++]=e;f=Da(a);e=f.length;for(var g=0;g<e;g++)b.call(c,f[g],d&&d[g],a)}};var Fa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Ha=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var e=a[c].substring(0,d);f=a[c].substring(d+1)}else e=a[c];b(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var M=function(a,b){this.G=this.L=this.J="";this.P=null;this.K=this.B="";this.u=this.ka=!1;if(a instanceof M){this.u=void 0!==b?b:a.u;Ia(this,a.J);var c=a.L;N(this);this.L=c;c=a.G;N(this);this.G=c;Ja(this,a.P);c=a.B;N(this);this.B=c;Ka(this,a.l.clone());a=a.K;N(this);this.K=a}else a&&(c=String(a).match(Fa))?(this.u=!!b,Ia(this,c[1]||"",!0),a=c[2]||"",N(this),this.L=O(a),a=c[3]||"",N(this),this.G=O(a,!0),Ja(this,c[4]),a=c[5]||"",N(this),this.B=O(a,!0),Ka(this,c[6]||"",!0),a=c[7]||"",N(this),this.K=
O(a)):(this.u=!!b,this.l=new P(null,this.u))};M.prototype.toString=function(){var a=[],b=this.J;b&&a.push(Q(b,La,!0),":");var c=this.G;if(c||"file"==b)a.push("//"),(b=this.L)&&a.push(Q(b,La,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.P,null!=c&&a.push(":",String(c));if(c=this.B)this.G&&"/"!=c.charAt(0)&&a.push("/"),a.push(Q(c,"/"==c.charAt(0)?Ma:Na,!0));(c=this.l.toString())&&a.push("?",c);(c=this.K)&&a.push("#",Q(c,Oa));return a.join("")};
M.prototype.resolve=function(a){var b=this.clone(),c=!!a.J;c?Ia(b,a.J):c=!!a.L;if(c){var d=a.L;N(b);b.L=d}else c=!!a.G;c?(d=a.G,N(b),b.G=d):c=null!=a.P;d=a.B;if(c)Ja(b,a.P);else if(c=!!a.B){if("/"!=d.charAt(0))if(this.G&&!this.B)d="/"+d;else{var f=b.B.lastIndexOf("/");-1!=f&&(d=b.B.substr(0,f+1)+d)}f=d;if(".."==f||"."==f)d="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){d=0==f.lastIndexOf("/",0);f=f.split("/");for(var e=[],g=0;g<f.length;){var k=f[g++];"."==k?d&&g==f.length&&e.push(""):".."==
k?((1<e.length||1==e.length&&""!=e[0])&&e.pop(),d&&g==f.length&&e.push("")):(e.push(k),d=!0)}d=e.join("/")}else d=f}c?(N(b),b.B=d):c=""!==a.l.toString();c?Ka(b,a.l.clone()):c=!!a.K;c&&(a=a.K,N(b),b.K=a);return b};M.prototype.clone=function(){return new M(this)};
var Ia=function(a,b,c){N(a);a.J=c?O(b,!0):b;a.J&&(a.J=a.J.replace(/:$/,""))},Ja=function(a,b){N(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.P=b}else a.P=null},Ka=function(a,b,c){N(a);b instanceof P?(a.l=b,a.l.Y(a.u)):(c||(b=Q(b,Pa)),a.l=new P(b,a.u))};M.prototype.getQuery=function(){return this.l.toString()};M.prototype.removeParameter=function(a){N(this);this.l.remove(a);return this};var N=function(a){if(a.ka)throw Error("Tried to modify a read-only Uri");};
M.prototype.Y=function(a){this.u=a;this.l&&this.l.Y(a)};
var O=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Q=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Qa),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Qa=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},La=/[#\/\?@]/g,Na=/[#\?:]/g,Ma=/[#\?]/g,Pa=/[#\?@]/g,Oa=/#/g,P=function(a,b){this.g=this.i=null;this.o=a||null;this.u=!!b},R=function(a){a.i||(a.i=new I,a.g=0,a.o&&Ha(a.o,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};h=P.prototype;h.ca=function(){R(this);return this.g};h.add=function(a,b){R(this);this.o=null;a=S(this,a);var c=this.i.get(a);c||this.i.set(a,c=[]);c.push(b);this.g=C(this.g)+1;return this};h.remove=function(a){R(this);a=S(this,a);return this.i.R(a)?(this.o=null,this.g=C(this.g)-this.i.get(a).length,this.i.remove(a)):!1};h.clear=function(){this.i=this.o=null;this.g=0};h.R=function(a){R(this);a=S(this,a);return this.i.R(a)};
h.forEach=function(a,b){R(this);this.i.forEach(function(c,d){ba(c,function(f){a.call(b,f,d,this)},this)},this)};h.I=function(){R(this);for(var a=this.i.A(),b=this.i.I(),c=[],d=0;d<b.length;d++)for(var f=a[d],e=0;e<f.length;e++)c.push(b[d]);return c};h.A=function(a){R(this);var b=[];if("string"===typeof a)this.R(a)&&(b=ca(b,this.i.get(S(this,a))));else{a=this.i.A();for(var c=0;c<a.length;c++)b=ca(b,a[c])}return b};
h.set=function(a,b){R(this);this.o=null;a=S(this,a);this.R(a)&&(this.g=C(this.g)-this.i.get(a).length);this.i.set(a,[b]);this.g=C(this.g)+1;return this};h.get=function(a,b){if(!a)return b;a=this.A(a);return 0<a.length?String(a[0]):b};
h.toString=function(){if(this.o)return this.o;if(!this.i)return"";for(var a=[],b=this.i.I(),c=0;c<b.length;c++){var d=b[c],f=encodeURIComponent(String(d));d=this.A(d);for(var e=0;e<d.length;e++){var g=f;""!==d[e]&&(g+="="+encodeURIComponent(String(d[e])));a.push(g)}}return this.o=a.join("&")};h.clone=function(){var a=new P;a.o=this.o;this.i&&(a.i=this.i.clone(),a.g=this.g);return a};var S=function(a,b){b=String(b);a.u&&(b=b.toLowerCase());return b};
P.prototype.Y=function(a){a&&!this.u&&(R(this),this.o=null,this.i.forEach(function(b,c){var d=c.toLowerCase();if(c!=d&&(this.remove(c),this.remove(d),0<b.length)){this.o=null;c=this.i;var f=c.set;d=S(this,d);var e=b.length;if(0<e){for(var g=Array(e),k=0;k<e;k++)g[k]=b[k];e=g}else e=[];f.call(c,d,e);this.g=C(this.g)+b.length}},this));this.u=a};P.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)Ea(arguments[b],function(c,d){this.add(d,c)},this)};var Ra={ma:!0},T=function(){throw Error("Do not instantiate directly");};T.prototype.V=null;T.prototype.getContent=function(){return this.content};T.prototype.toString=function(){return this.content};var U=function(){T.call(this)};t(U,T);U.prototype.aa=Ra;var Sa=function(a){var b=null!=a&&a.aa===Ra;b&&A(a.constructor===U);return b};var Ta=function(a){if(null!=a)switch(a.V){case 1:return 1;case -1:return-1;case 0:return 0}return null},Wa=function(a){return Sa(a)?a:a instanceof H?Ua(oa(a).toString(),a.ba):Ua(Va(String(a)),Ta(a))},Ua=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.V=d);return c}}(U),V=function(a){if(Sa(a)){var b=String;a=a.getContent();a=String(a).replace(Xa,"").replace(Ya,"&lt;");b=b(a).replace(Za,$a)}else b=Va(a);return b},Va=function(a){a=
String(a);return a=la(a,void 0)},ab={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},$a=function(a){return ab[a]},Za=/[\x00\x22\x27\x3c\x3e]/g,Xa=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,Ya=/</g;var W=function(a,b){this.text=a;this.type=b},bb=function(a,b){this.spans=a;this.type=b},cb="break case catch continue debugger default delete do else finally for function if in instanceof new return switch this throw try typeof var void while with false null undefined true abstract boolean byte char const double final float goto int long native short synchronized throws transient volatile class enum export extends import super implements interface let package private protected public static yield".split(" "),
db=function(a,b){try{var c=new XMLHttpRequest;c.open("GET",a,!0);var d=!1;c.onreadystatechange=function(){d||4!=c.readyState||200!=c.status||(d=!0,b(c))};c.send()}catch(f){}},X={type:"html-tag",open:/^<\/?([-_a-zA-Z0-9]+)/,close:/^(\/?)>/,fa:function(a,b){a.W=b[1].toUpperCase();return!0},U:function(a,b){""==b[1]&&("SCRIPT"==a.W?(a.F="js-code",a.O=null,a.S=eb):"STYLE"==a.W&&(a.F="css-code",a.O=null,a.S=fb));return!0}},gb=[{type:"html-comment",open:"\x3c!--",close:"--\x3e"},{type:"html-cdata",open:"<![CDATA[",
close:"]]\x3e"},{type:"html-doctype",open:"<!",close:">"},X,{type:"html-attribute-url",open:/^"(https?|\/\/)/,close:'"',escape:"\\",C:X},{type:"html-attribute-url",open:/^'(https?|\/\/)/,close:"'",escape:"\\",C:X},{type:"html-attribute-value",open:'"',close:'"',escape:"\\",C:X},{type:"html-attribute-value",open:"'",close:"'",escape:"\\",C:X},{type:"html-attribute-name",open:/(^[-_a-zA-Z0-9]+)/,close:"=",C:X}],eb=[{type:"js-comment",open:"//",N:!0},{type:"js-comment",open:"/*",close:"*/"},{type:"js-string",
open:'"',close:'"',escape:"\\",N:!0},{type:"js-regex",open:"/",close:"/",escape:"\\",N:!0},{open:/^\.[a-zA-Z_][a-zA-Z_0-9]*/,H:!0},{type:"js-keyword",open:/^[a-zA-Z_][a-zA-Z_0-9]*/,fa:function(a,b){return 0<=cb.indexOf(b[0])},H:!0},{open:/^[a-zA-Z_][a-zA-Z_0-9.]*/,H:!0},{type:"js-number",open:/^[+-]?[0-9.]+/,H:!0},{type:"js-string",open:"'",close:"'",escape:"\\",N:!0},{type:"html-tag",open:/^\s*<\/script/,close:/>/,U:function(a){a.F=null;a.O=null;a.S=gb;return!0}}],hb={open:"{",close:"}"},Y={open:":",
close:";",C:hb},fb=[{type:"css-comment",open:"\x3c!--",close:">"},{type:"css-comment",open:"/*",close:"*/"},{type:"css-string",open:'"',close:'"',escape:"\\",N:!0},{type:"css-number",open:/^[+-]?[0-9.]+[a-zA-Z]*/,H:!0,C:Y},{type:"css-color",open:/^#[0-9a-zA-Z]{3}[0-9a-zA-Z]{0,3}/,H:!0,C:Y},hb,Y,{type:"css-name",open:/^[-.#_a-zA-Z0-9]+/,H:!0,C:hb},{type:"css-attribute-value",open:/^[-a-zA-Z_0-9]+/,H:!0,C:Y},{type:"css-string",open:"'",close:"'",escape:"\\",N:!0},{type:"html-tag",open:/^\s*<\/style/,
close:/>/,U:function(a){a.S=gb;a.F=null;a.O=null;return!0}}],jb=function(a){var b={S:gb,W:null,O:null,F:null},c=[],d=[null],f=[null],e=void 0;a=ya(a);a.split("\n").forEach(function(g){var k=[],n=0;b.O=b.F;for(var l=0,J=g.length;l<J;l+=w?0:1){var w=!1;if(!e||e.escape!=g.charAt(l)){if(e){var v=e.close?ib(b,e.close,g,l,e.U):0;v&&(l+=v,k.push(new W(g.substring(n,l),e.type||b.F)),n=l,d.pop(),f.pop(),e=f[f.length-1],w=!0)}for(var Ga=0,r;!w&&(r=b.S[Ga]);Ga++)r.C==e&&(v=ib(b,r.open,g,l,r.fa))&&(l>n&&r.type!=
d[d.length-1]&&(k.push(new W(g.substring(n,l),d[d.length-1]||b.F)),n=l),l+=v,r.H?(k.push(new W(g.substring(n,l),r.type||b.F)),n=l):(d.push(r.type),f.push(r),e=r),w=!0)}}n<J&&k.push(new W(g.substring(n,J),d[d.length-1]||b.F));c.push(new bb(k,b.O));e&&e.N&&(d.pop(),f.pop(),e=f[f.length-1])});return c},ib=function(a,b,c,d,f){var e;return b.exec&&(e=b.exec(c.substring(d)))?f&&!f(a,e)?0:e[0].length:c.substring(d,d+b.length)==b?b.length:0};var Z,kb=document.location.href;Z=kb instanceof M?kb.clone():new M(kb,void 0);
(function(a,b,c){db(a,function(d){var f=document.getElementById("source");d=jb(d.response+"");for(var e=c||1,g='<div class="header"><h1 id="title">Source: '+Wa(a)+"</h1>"+(a?'<a id="view-source" href="view-source:'+V(a)+"\">View Source in Chrome's Source code viewer</a>":"")+'</div><div class="line-gutter-backdrop"></div><table><tbody>',k=d.length,n=0;n<k;n++){var l=d[n];g+="<tr"+(l.type?' class="'+V(l.type)+'"':"")+'><td class="line-number'+(n+1>=b&&n+1<=b+e?" highlight":"")+'" data-value="'+V(n+
1)+'"></td><td class="line-content">';l=l.spans;for(var J=l.length,w=0;w<J;w++){var v=l[w];g+=v.type?'<span class="'+V(v.type)+'">'+Wa(v.text)+"</span>":Wa(v.text)}g+="</td></tr>"}d=Ua(g+"</tbody></table>");e=typeof d;if("object"==e&&null!=d||"function"==e)if(d instanceof T){if(d.aa!==Ra)throw Error("Sanitized content was not of kind HTML.");d=sa(new F(E,"Soy SanitizedContent of kind HTML produces SafeHtml-contract-compliant value."),d.toString(),d.V)}else B("Soy template output is unsafe for use as HTML: "+
d),d=qa("zSoyz");else d=qa(String(d));va(A(f),d);f=b||0;d=0;e=document;e=e.querySelectorAll&&e.querySelector?e.querySelectorAll("TR"):e.getElementsByTagName("TR");0<=f&&f<e.length&&(d=e[f].offsetTop);window.scrollTo(0,d)})})(Z.l.get("url")||"",parseInt(Z.l.get("line")||-1,10),parseInt(Z.l.get("count")||0,10));
